#
# Copyright (C) 2019 Onion Corporation
#
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk
PKG_NAME:={{name}}
PKG_VERSION:=1.0.0
PKG_RELEASE:=1


PKG_SOURCE_PROTO:=git
PKG_SOURCE_VERSION:=HEAD # dev for dev branch, HEAD for master
PKG_SOURCE_URL:={{repo}}
PKG_SOURCE_SUBDIR:=$(PKG_NAME)
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_RELEASE).tar.gz
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk

define Package/{{name}}
	SECTION:=onion
	CATEGORY:=Onion
	SUBMENU:={{submenu}}
	TITLE:={{description}}
{{#if dependencies}}
	DEPENDS:={{dependencies}}
{{/if}}
endef


define Package/{{name}}/description
{{description}}
endef

define Package/{{name}}/install
{{#each files}}
  $(INSTALL_DIR) $(1){{this.destination.directory}}
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/{{this.source}} $(1){{this.destination.directory}}/{{this.destination.filename}}
{{/each}}
endef


# calls to build package
$(eval $(call BuildPackage,{{name}}))
